# Generated by Django 5.2.2 on 2025-06-15 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('depart_lat', models.FloatField(blank=True, null=True)),
                ('depart_lng', models.FloatField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('conducteur', models.BooleanField(default=False)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('places', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
