# Generated by Django 5.2.2 on 2025-06-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='modele',
            new_name='model',
        ),
    ]
