# Generated by Django 5.2.2 on 2025-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0002_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Role',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
