# Generated by Django 5.2.2 on 2025-06-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0002_rename_modele_profil_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='depart_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='depart_lng',
            new_name='longitude',
        ),
    ]
