# Generated by Django 5.2.2 on 2025-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0003_rename_depart_lat_profil_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nom',
            field=models.CharField(default='COMOTORAGE', max_length=15),
        ),
        migrations.AddField(
            model_name='profil',
            name='prénom',
            field=models.CharField(default='Ifri', max_length=15),
        ),
    ]
