# Generated by Django 5.2.2 on 2025-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentificate_user', '0004_profil_nom_profil_prénom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='prénom',
            field=models.CharField(max_length=100),
        ),
    ]
