# Generated by Django 5.2.3 on 2025-06-16 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentificate_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departlatitude', models.CharField(max_length=200)),
                ('departlongitude', models.CharField(max_length=200)),
                ('arriveelatitude', models.CharField(max_length=200)),
                ('arriveelongitude', models.CharField(max_length=200)),
                ('departTime', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentificate_user.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departlatitude', models.CharField(max_length=200)),
                ('departlongitude', models.CharField(max_length=200)),
                ('arriveelatitude', models.CharField(max_length=200)),
                ('arriveelongitude', models.CharField(max_length=200)),
                ('departTime', models.TimeField(default=django.utils.timezone.now)),
                ('nbPLacesDispo', models.PositiveIntegerField(default=5)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentificate_user.profil')),
            ],
        ),
    ]
