# Generated by Django 5.2.2 on 2025-06-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='driver',
        ),
        migrations.AlterField(
            model_name='demande',
            name='arriveelatitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='arriveelongitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departlatitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='departlongitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offre',
            name='arriveelatitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offre',
            name='arriveelongitude',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offre',
            name='departlatitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offre',
            name='departlongitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offre',
            name='nbPLacesDispo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
